// Copyright (c) 2023-present, Trail of Bits, Inc.
// All rights reserved.
//
// This source code is licensed in accordance with the terms specified in
// the LICENSE file found in the root directory of this source tree.

// Auto-generated file; do not modify!

#pragma once

#include <cstdint>

namespace mx {
enum class DeclKind : uint8_t;
enum class AttrKind : uint16_t;
enum class AArch64SVEPcsAttrSpelling : uint8_t;
enum class AArch64VectorPcsAttrSpelling : uint8_t;
enum class AMDGPUFlatWorkGroupSizeAttrSpelling : uint8_t;
enum class AMDGPUKernelCallAttrSpelling : uint8_t;
enum class AMDGPUNumSGPRAttrSpelling : uint8_t;
enum class AMDGPUNumVGPRAttrSpelling : uint8_t;
enum class AMDGPUWavesPerEUAttrSpelling : uint8_t;
enum class ARMInterruptAttrInterruptType : uint8_t;
enum class ARMInterruptAttrSpelling : uint8_t;
enum class AVRInterruptAttrSpelling : uint8_t;
enum class AVRSignalAttrSpelling : uint8_t;
enum class AbiTagAttrSpelling : uint8_t;
enum class AcquireCapabilityAttrSpelling : uint8_t;
enum class AcquireHandleAttrSpelling : uint8_t;
enum class AddressSpaceAttrSpelling : uint8_t;
enum class AliasAttrSpelling : uint8_t;
enum class AlignedAttrSpelling : uint8_t;
enum class AllocAlignAttrSpelling : uint8_t;
enum class AllocSizeAttrSpelling : uint8_t;
enum class AlwaysDestroyAttrSpelling : uint8_t;
enum class AlwaysInlineAttrSpelling : uint8_t;
enum class AnnotateAttrSpelling : uint8_t;
enum class AnnotateTypeAttrSpelling : uint8_t;
enum class AnyX86InterruptAttrSpelling : uint8_t;
enum class AnyX86NoCallerSavedRegistersAttrSpelling : uint8_t;
enum class AnyX86NoCfCheckAttrSpelling : uint8_t;
enum class ArcWeakrefUnavailableAttrSpelling : uint8_t;
enum class ArgumentWithTypeTagAttrSpelling : uint8_t;
enum class ArmBuiltinAliasAttrSpelling : uint8_t;
enum class ArmMveStrictPolymorphismAttrSpelling : uint8_t;
enum class ArrayTypeArraySizeModifier : uint8_t;
enum class ArtificialAttrSpelling : uint8_t;
enum class AsmLabelAttrSpelling : uint8_t;
enum class AssertCapabilityAttrSpelling : uint8_t;
enum class AssumeAlignedAttrSpelling : uint8_t;
enum class AssumptionAttrSpelling : uint8_t;
enum class AtomicExprAtomicOp : uint8_t;
enum class AvailabilityAttrSpelling : uint8_t;
enum class AvailableOnlyInDefaultEvalMethodAttrSpelling : uint8_t;
enum class BPFPreserveAccessIndexAttrSpelling : uint8_t;
enum class BTFDeclTagAttrSpelling : uint8_t;
enum class BTFTypeTagAttrSpelling : uint8_t;
enum class BlocksAttrBlockType : uint8_t;
enum class BlocksAttrSpelling : uint8_t;
enum class BuiltinAliasAttrSpelling : uint8_t;
enum class BuiltinTypeKind : uint16_t;
enum class CDeclAttrSpelling : uint8_t;
enum class CFAuditedTransferAttrSpelling : uint8_t;
enum class CFConsumedAttrSpelling : uint8_t;
enum class CFGuardAttrGuardArg : uint8_t;
enum class CFGuardAttrSpelling : uint8_t;
enum class CFICanonicalJumpTableAttrSpelling : uint8_t;
enum class CFReturnsNotRetainedAttrSpelling : uint8_t;
enum class CFReturnsRetainedAttrSpelling : uint8_t;
enum class CFUnknownTransferAttrSpelling : uint8_t;
enum class CPUDispatchAttrSpelling : uint8_t;
enum class CPUSpecificAttrSpelling : uint8_t;
enum class CUDAConstantAttrSpelling : uint8_t;
enum class CUDADeviceAttrSpelling : uint8_t;
enum class CUDADeviceBuiltinSurfaceTypeAttrSpelling : uint8_t;
enum class CUDADeviceBuiltinTextureTypeAttrSpelling : uint8_t;
enum class CUDAGlobalAttrSpelling : uint8_t;
enum class CUDAHostAttrSpelling : uint8_t;
enum class CUDALaunchBoundsAttrSpelling : uint8_t;
enum class CUDASharedAttrSpelling : uint8_t;
enum class CXX11NoReturnAttrSpelling : uint8_t;
enum class CXXConstructExprConstructionKind : uint8_t;
enum class CXXNewExprInitializationStyle : uint8_t;
enum class CXXRecordDeclLambdaDependencyKind : uint8_t;
enum class CallExprADLCallKind : uint8_t;
enum class CallableWhenAttrConsumedState : uint8_t;
enum class CallableWhenAttrSpelling : uint8_t;
enum class CallbackAttrSpelling : uint8_t;
enum class CalledOnceAttrSpelling : uint8_t;
enum class CapabilityAttrSpelling : uint8_t;
enum class CapturedStmtVariableCaptureKind : uint8_t;
enum class CarriesDependencyAttrSpelling : uint8_t;
enum class CharacterLiteralCharacterKind : uint8_t;
enum class CleanupAttrSpelling : uint8_t;
enum class ColdAttrSpelling : uint8_t;
enum class CommonAttrSpelling : uint8_t;
enum class ConstAttrSpelling : uint8_t;
enum class ConstInitAttrSpelling : uint8_t;
enum class ConstantExprResultStorageKind : uint8_t;
enum class ConstructorAttrSpelling : uint8_t;
enum class ConsumableAttrConsumedState : uint8_t;
enum class ConsumableAttrSpelling : uint8_t;
enum class ConsumableAutoCastAttrSpelling : uint8_t;
enum class ConsumableSetOnReadAttrSpelling : uint8_t;
enum class ConvergentAttrSpelling : uint8_t;
enum class DLLExportAttrSpelling : uint8_t;
enum class DLLImportAttrSpelling : uint8_t;
enum class DeclFriendObjectKind : uint8_t;
enum class DeclIdentifierNamespace : uint8_t;
enum class DeclModuleOwnershipKind : uint8_t;
enum class DeclObjCDeclQualifier : uint8_t;
enum class DeprecatedAttrSpelling : uint8_t;
enum class DestructorAttrSpelling : uint8_t;
enum class DiagnoseAsBuiltinAttrSpelling : uint8_t;
enum class DiagnoseIfAttrDiagnosticType : uint8_t;
enum class DisableSanitizerInstrumentationAttrSpelling : uint8_t;
enum class DisableTailCallsAttrSpelling : uint8_t;
enum class EnforceTCBAttrSpelling : uint8_t;
enum class EnforceTCBLeafAttrSpelling : uint8_t;
enum class EnumExtensibilityAttrKind : uint8_t;
enum class EnumExtensibilityAttrSpelling : uint8_t;
enum class ErrorAttrSpelling : uint8_t;
enum class ExcludeFromExplicitInstantiationAttrSpelling : uint8_t;
enum class ExprConstantExprKind : uint8_t;
enum class ExprLValueClassification : uint8_t;
enum class ExprNullPointerConstantKind : uint8_t;
enum class ExprNullPointerConstantValueDependence : uint8_t;
enum class ExprSideEffectsKind : uint8_t;
enum class ExprisModifiableLvalueResult : uint8_t;
enum class ExternalSourceSymbolAttrSpelling : uint8_t;
enum class FallThroughAttrSpelling : uint8_t;
enum class FastCallAttrSpelling : uint8_t;
enum class FinalAttrSpelling : uint8_t;
enum class FlagEnumAttrSpelling : uint8_t;
enum class FlattenAttrSpelling : uint8_t;
enum class FormatArgAttrSpelling : uint8_t;
enum class FormatAttrSpelling : uint8_t;
enum class FunctionDeclTemplatedKind : uint8_t;
enum class FunctionReturnThunksAttrKind : uint8_t;
enum class FunctionReturnThunksAttrSpelling : uint8_t;
enum class GNUInlineAttrSpelling : uint8_t;
enum class GuardedVarAttrSpelling : uint8_t;
enum class HIPManagedAttrSpelling : uint8_t;
enum class HLSLResourceAttrResourceClass : uint8_t;
enum class HLSLResourceAttrResourceKind : uint8_t;
enum class HLSLShaderAttrShaderType : uint8_t;
enum class HotAttrSpelling : uint8_t;
enum class IBActionAttrSpelling : uint8_t;
enum class IBOutletAttrSpelling : uint8_t;
enum class IBOutletCollectionAttrSpelling : uint8_t;
enum class IFuncAttrSpelling : uint8_t;
enum class ImplicitCastExprOnStack : uint8_t;
enum class ImplicitParamDeclImplicitParamKind : uint8_t;
enum class InitPriorityAttrSpelling : uint8_t;
enum class IntelOclBiccAttrSpelling : uint8_t;
enum class InternalLinkageAttrSpelling : uint8_t;
enum class LTOVisibilityPublicAttrSpelling : uint8_t;
enum class LeafAttrSpelling : uint8_t;
enum class LifetimeBoundAttrSpelling : uint8_t;
enum class LikelyAttrSpelling : uint8_t;
enum class LinkageSpecDeclLanguageIDs : uint8_t;
enum class LoaderUninitializedAttrSpelling : uint8_t;
enum class LoopHintAttrLoopHintState : uint8_t;
enum class LoopHintAttrOptionType : uint8_t;
enum class LoopHintAttrSpelling : uint8_t;
enum class MIGServerRoutineAttrSpelling : uint8_t;
enum class MSABIAttrSpelling : uint8_t;
enum class MSInheritanceAttrSpelling : uint8_t;
enum class MSP430InterruptAttrSpelling : uint8_t;
enum class MSStructAttrSpelling : uint8_t;
enum class MayAliasAttrSpelling : uint8_t;
enum class MaybeUndefAttrSpelling : uint8_t;
enum class MicroMipsAttrSpelling : uint8_t;
enum class MinSizeAttrSpelling : uint8_t;
enum class MinVectorWidthAttrSpelling : uint8_t;
enum class Mips16AttrSpelling : uint8_t;
enum class MipsInterruptAttrInterruptType : uint8_t;
enum class MipsInterruptAttrSpelling : uint8_t;
enum class MipsLongCallAttrSpelling : uint8_t;
enum class MipsShortCallAttrSpelling : uint8_t;
enum class ModeAttrSpelling : uint8_t;
enum class MustTailAttrSpelling : uint8_t;
enum class NSConsumedAttrSpelling : uint8_t;
enum class NSConsumesSelfAttrSpelling : uint8_t;
enum class NSReturnsAutoreleasedAttrSpelling : uint8_t;
enum class NSReturnsNotRetainedAttrSpelling : uint8_t;
enum class NSReturnsRetainedAttrSpelling : uint8_t;
enum class NVPTXKernelAttrSpelling : uint8_t;
enum class NakedAttrSpelling : uint8_t;
enum class NamedDeclExplicitVisibilityKind : uint8_t;
enum class NoBuiltinAttrSpelling : uint8_t;
enum class NoCommonAttrSpelling : uint8_t;
enum class NoDebugAttrSpelling : uint8_t;
enum class NoDerefAttrSpelling : uint8_t;
enum class NoDestroyAttrSpelling : uint8_t;
enum class NoDuplicateAttrSpelling : uint8_t;
enum class NoEscapeAttrSpelling : uint8_t;
enum class NoInlineAttrSpelling : uint8_t;
enum class NoInstrumentFunctionAttrSpelling : uint8_t;
enum class NoMergeAttrSpelling : uint8_t;
enum class NoMicroMipsAttrSpelling : uint8_t;
enum class NoMips16AttrSpelling : uint8_t;
enum class NoProfileFunctionAttrSpelling : uint8_t;
enum class NoRandomizeLayoutAttrSpelling : uint8_t;
enum class NoReturnAttrSpelling : uint8_t;
enum class NoSanitizeAttrSpelling : uint8_t;
enum class NoSpeculativeLoadHardeningAttrSpelling : uint8_t;
enum class NoSplitStackAttrSpelling : uint8_t;
enum class NoStackProtectorAttrSpelling : uint8_t;
enum class NoThreadSafetyAnalysisAttrSpelling : uint8_t;
enum class NoThrowAttrSpelling : uint8_t;
enum class NoUwtableAttrSpelling : uint8_t;
enum class NonNullAttrSpelling : uint8_t;
enum class NotTailCalledAttrSpelling : uint8_t;
enum class OMPAllocateDeclAttrAllocatorTypeTy : uint8_t;
enum class OMPDeclareReductionDeclInitKind : uint8_t;
enum class OMPDeclareSimdDeclAttrBranchStateTy : uint8_t;
enum class OMPDeclareTargetDeclAttrDevTypeTy : uint8_t;
enum class OMPDeclareTargetDeclAttrMapTypeTy : uint8_t;
enum class OSConsumedAttrSpelling : uint8_t;
enum class OSConsumesThisAttrSpelling : uint8_t;
enum class OSReturnsNotRetainedAttrSpelling : uint8_t;
enum class OSReturnsRetainedAttrSpelling : uint8_t;
enum class OSReturnsRetainedOnNonZeroAttrSpelling : uint8_t;
enum class OSReturnsRetainedOnZeroAttrSpelling : uint8_t;
enum class ObjCBoxableAttrSpelling : uint8_t;
enum class ObjCBridgeAttrSpelling : uint8_t;
enum class ObjCBridgeMutableAttrSpelling : uint8_t;
enum class ObjCBridgeRelatedAttrSpelling : uint8_t;
enum class ObjCClassStubAttrSpelling : uint8_t;
enum class ObjCDesignatedInitializerAttrSpelling : uint8_t;
enum class ObjCDirectAttrSpelling : uint8_t;
enum class ObjCDirectMembersAttrSpelling : uint8_t;
enum class ObjCExceptionAttrSpelling : uint8_t;
enum class ObjCExplicitProtocolImplAttrSpelling : uint8_t;
enum class ObjCExternallyRetainedAttrSpelling : uint8_t;
enum class ObjCGCAttrSpelling : uint8_t;
enum class ObjCIndependentClassAttrSpelling : uint8_t;
enum class ObjCIvarDeclAccessControl : uint8_t;
enum class ObjCMessageExprReceiverKind : uint8_t;
enum class ObjCMethodDeclImplementationControl : uint8_t;
enum class ObjCMethodFamilyAttrFamilyKind : uint8_t;
enum class ObjCMethodFamilyAttrSpelling : uint8_t;
enum class ObjCNSObjectAttrSpelling : uint8_t;
enum class ObjCNonLazyClassAttrSpelling : uint8_t;
enum class ObjCNonRuntimeProtocolAttrSpelling : uint8_t;
enum class ObjCOwnershipAttrSpelling : uint8_t;
enum class ObjCPreciseLifetimeAttrSpelling : uint8_t;
enum class ObjCPropertyDeclPropertyControl : uint8_t;
enum class ObjCPropertyDeclSetterKind : uint8_t;
enum class ObjCPropertyImplDeclKind : uint8_t;
enum class ObjCRequiresPropertyDefsAttrSpelling : uint8_t;
enum class ObjCRequiresSuperAttrSpelling : uint8_t;
enum class ObjCReturnsInnerPointerAttrSpelling : uint8_t;
enum class ObjCRootClassAttrSpelling : uint8_t;
enum class ObjCRuntimeNameAttrSpelling : uint8_t;
enum class ObjCRuntimeVisibleAttrSpelling : uint8_t;
enum class ObjCSubclassingRestrictedAttrSpelling : uint8_t;
enum class OpenCLAccessAttrSpelling : uint8_t;
enum class OpenCLConstantAddressSpaceAttrSpelling : uint8_t;
enum class OpenCLGenericAddressSpaceAttrSpelling : uint8_t;
enum class OpenCLGlobalAddressSpaceAttrSpelling : uint8_t;
enum class OpenCLGlobalDeviceAddressSpaceAttrSpelling : uint8_t;
enum class OpenCLGlobalHostAddressSpaceAttrSpelling : uint8_t;
enum class OpenCLKernelAttrSpelling : uint8_t;
enum class OpenCLLocalAddressSpaceAttrSpelling : uint8_t;
enum class OpenCLPrivateAddressSpaceAttrSpelling : uint8_t;
enum class OptimizeNoneAttrSpelling : uint8_t;
enum class OverloadableAttrSpelling : uint8_t;
enum class OwnershipAttrOwnershipKind : uint8_t;
enum class OwnershipAttrSpelling : uint8_t;
enum class PackedAttrSpelling : uint8_t;
enum class ParamTypestateAttrConsumedState : uint8_t;
enum class ParamTypestateAttrSpelling : uint8_t;
enum class PascalAttrSpelling : uint8_t;
enum class PassObjectSizeAttrSpelling : uint8_t;
enum class PatchableFunctionEntryAttrSpelling : uint8_t;
enum class PcsAttrPCSType : uint8_t;
enum class PcsAttrSpelling : uint8_t;
enum class PredefinedExprIdentKind : uint8_t;
enum class PreferredNameAttrSpelling : uint8_t;
enum class PreserveAllAttrSpelling : uint8_t;
enum class PreserveMostAttrSpelling : uint8_t;
enum class PtGuardedVarAttrSpelling : uint8_t;
enum class PureAttrSpelling : uint8_t;
enum class QualifiedTypeDestructionKind : uint8_t;
enum class QualifiedTypePrimitiveCopyKind : uint8_t;
enum class QualifiedTypePrimitiveDefaultInitializeKind : uint8_t;
enum class RISCVInterruptAttrInterruptType : uint8_t;
enum class RISCVInterruptAttrSpelling : uint8_t;
enum class RandomizeLayoutAttrSpelling : uint8_t;
enum class ReadOnlyPlacementAttrSpelling : uint8_t;
enum class RecordDeclArgPassingKind : uint8_t;
enum class RegCallAttrSpelling : uint8_t;
enum class ReinitializesAttrSpelling : uint8_t;
enum class ReleaseCapabilityAttrSpelling : uint8_t;
enum class ReleaseHandleAttrSpelling : uint8_t;
enum class RequiresCapabilityAttrSpelling : uint8_t;
enum class RestrictAttrSpelling : uint8_t;
enum class RetainAttrSpelling : uint8_t;
enum class ReturnTypestateAttrConsumedState : uint8_t;
enum class ReturnTypestateAttrSpelling : uint8_t;
enum class ReturnsNonNullAttrSpelling : uint8_t;
enum class ReturnsTwiceAttrSpelling : uint8_t;
enum class SYCLKernelAttrSpelling : uint8_t;
enum class SYCLSpecialClassAttrSpelling : uint8_t;
enum class ScopedLockableAttrSpelling : uint8_t;
enum class SectionAttrSpelling : uint8_t;
enum class SelectAnyAttrSpelling : uint8_t;
enum class SentinelAttrSpelling : uint8_t;
enum class SetTypestateAttrConsumedState : uint8_t;
enum class SetTypestateAttrSpelling : uint8_t;
enum class SourceLocExprIdentKind : uint8_t;
enum class SpeculativeLoadHardeningAttrSpelling : uint8_t;
enum class StandaloneDebugAttrSpelling : uint8_t;
enum class StdCallAttrSpelling : uint8_t;
enum class StmtLikelihood : uint8_t;
enum class StmtKind : uint8_t;
enum class StringLiteralStringKind : uint8_t;
enum class SwiftAsyncAttrKind : uint8_t;
enum class SwiftAsyncAttrSpelling : uint8_t;
enum class SwiftAsyncCallAttrSpelling : uint8_t;
enum class SwiftAsyncContextAttrSpelling : uint8_t;
enum class SwiftAsyncErrorAttrConventionKind : uint8_t;
enum class SwiftAsyncErrorAttrSpelling : uint8_t;
enum class SwiftCallAttrSpelling : uint8_t;
enum class SwiftContextAttrSpelling : uint8_t;
enum class SwiftErrorAttrConventionKind : uint8_t;
enum class SwiftErrorResultAttrSpelling : uint8_t;
enum class SwiftIndirectResultAttrSpelling : uint8_t;
enum class SwiftNewTypeAttrNewtypeKind : uint8_t;
enum class SwiftNewTypeAttrSpelling : uint8_t;
enum class SysVABIAttrSpelling : uint8_t;
enum class TLSModelAttrSpelling : uint8_t;
enum class TargetAttrSpelling : uint8_t;
enum class TargetClonesAttrSpelling : uint8_t;
enum class TargetVersionAttrSpelling : uint8_t;
enum class TemplateArgumentKind : uint8_t;
enum class TestTypestateAttrConsumedState : uint8_t;
enum class TestTypestateAttrSpelling : uint8_t;
enum class ThisCallAttrSpelling : uint8_t;
enum class TransparentUnionAttrSpelling : uint8_t;
enum class TrivialABIAttrSpelling : uint8_t;
enum class TryAcquireCapabilityAttrSpelling : uint8_t;
enum class TypeScalarTypeKind : uint8_t;
enum class TypeKind : uint8_t;
enum class TypeTagForDatatypeAttrSpelling : uint8_t;
enum class TypeVisibilityAttrSpelling : uint8_t;
enum class TypeVisibilityAttrVisibilityType : uint8_t;
enum class UnaryTransformTypeUTTKind : uint8_t;
enum class UnavailableAttrImplicitReason : uint8_t;
enum class UnavailableAttrSpelling : uint8_t;
enum class UninitializedAttrSpelling : uint8_t;
enum class UnlikelyAttrSpelling : uint8_t;
enum class UnsafeBufferUsageAttrSpelling : uint8_t;
enum class UnusedAttrSpelling : uint8_t;
enum class UseHandleAttrSpelling : uint8_t;
enum class UsedAttrSpelling : uint8_t;
enum class UserDefinedLiteralLiteralOperatorKind : uint8_t;
enum class UsingIfExistsAttrSpelling : uint8_t;
enum class UuidAttrSpelling : uint8_t;
enum class VarDeclDefinitionKind : uint8_t;
enum class VarDeclInitializationStyle : uint8_t;
enum class VarDeclTLSKind : uint8_t;
enum class VecReturnAttrSpelling : uint8_t;
enum class VectorCallAttrSpelling : uint8_t;
enum class VectorTypeVectorKind : uint8_t;
enum class VisibilityAttrSpelling : uint8_t;
enum class VisibilityAttrVisibilityType : uint8_t;
enum class WarnUnusedAttrSpelling : uint8_t;
enum class WarnUnusedResultAttrSpelling : uint8_t;
enum class WeakAttrSpelling : uint8_t;
enum class WeakImportAttrSpelling : uint8_t;
enum class WeakRefAttrSpelling : uint8_t;
enum class WebAssemblyExportNameAttrSpelling : uint8_t;
enum class WebAssemblyImportModuleAttrSpelling : uint8_t;
enum class WebAssemblyImportNameAttrSpelling : uint8_t;
enum class X86ForceAlignArgPointerAttrSpelling : uint8_t;
enum class XRayInstrumentAttrSpelling : uint8_t;
enum class XRayLogArgsAttrSpelling : uint8_t;
enum class ZeroCallUsedRegsAttrSpelling : uint8_t;
enum class ZeroCallUsedRegsAttrZeroCallUsedRegsKind : uint8_t;
enum class ASTDumpOutputFormat : uint8_t;
enum class AccessSpecifier : uint8_t;
enum class AddrSpaceMapMangling : uint8_t;
enum class AlignRequirementKind : uint8_t;
enum class AltivecSrcCompatKind : uint8_t;
enum class ArgumentKind : uint8_t;
enum class ArrayTypeTrait : uint8_t;
enum class AssignmentTrackingOpts : uint8_t;
enum class AtomicScopeModelKind : uint8_t;
enum class AutoTypeKeyword : uint8_t;
enum class AvailabilityResult : uint8_t;
enum class BinaryOperatorKind : uint8_t;
enum class Bits : uint8_t;
enum class CallingConv : uint8_t;
enum class CanThrowResult : uint8_t;
enum class CapturedRegionKind : uint8_t;
enum class CastKind : uint8_t;
enum class ClangABI : uint8_t;
enum class CommentKind : uint8_t;
enum class ComparisonCategoryResult : uint8_t;
enum class ComparisonCategoryType : uint8_t;
enum class CompilingModuleKind : uint8_t;
enum class ConstexprSpecKind : uint8_t;
enum class CoreFoundationABI : uint8_t;
enum class DataPositionTy : uint8_t;
enum class DebugSrcHashKind : uint8_t;
enum class DeductionCandidate : uint8_t;
enum class DefaultArgKind : uint8_t;
enum class DefaultCallingConvention : uint8_t;
enum class DefaultVisiblityExportMapping : uint8_t;
enum class DesignatorKind : uint8_t;
enum class DiagnosticLevelMask : uint8_t;
enum class ElaboratedTypeKeyword : uint8_t;
enum class EmbedBitcodeKind : uint8_t;
enum class EscapeChar : uint8_t;
enum class ExceptionHandlingKind : uint8_t;
enum class ExceptionSpecificationType : uint8_t;
enum class ExcessPrecisionKind : uint8_t;
enum class ExclusionType : uint8_t;
enum class ExplicitSpecKind : uint8_t;
enum class ExprDependence : uint8_t;
enum class ExprObjectKind : uint8_t;
enum class ExprOffsets : uint8_t;
enum class ExprValueKind : uint8_t;
enum class ExpressionTrait : uint8_t;
enum class ExtKind : uint8_t;
enum class ExtendArgsKind : uint8_t;
enum class FPEvalMethodKind : uint8_t;
enum class FPExceptionModeKind : uint8_t;
enum class FPModeKind : uint8_t;
enum class FiniteLoopsKind : uint8_t;
enum class Flags : uint8_t;
enum class FramePointerKind : uint8_t;
enum class GC : uint8_t;
enum class GCMode : uint8_t;
enum class GPUDefaultStreamKind : uint8_t;
enum class GVALinkage : uint8_t;
enum class GetBuiltinTypeError : uint8_t;
enum class HLSLLangStd : uint8_t;
enum class ID : uint8_t;
enum class IdentifierInfoFlag : uint8_t;
enum class IfStatementKind : uint8_t;
enum class ImbueAttribute : uint8_t;
enum class InClassInitStyle : uint8_t;
enum class InheritedDesignatedInitializersState : uint8_t;
enum class InitStorageKind : uint8_t;
enum class InlineAsmDialectKind : uint8_t;
enum class InlineVariableDefinitionKind : uint8_t;
enum class InliningMethod : uint8_t;
enum class InterestingIdentifierKind : uint8_t;
enum class Kinds : uint8_t;
enum class LambdaCaptureDefault : uint8_t;
enum class LambdaCaptureKind : uint8_t;
enum class LangAS : uint8_t;
enum class LangFeatures : uint8_t;
enum class Language : uint8_t;
enum class LanguageLinkage : uint8_t;
enum class LaxVectorConversionKind : uint8_t;
enum class Level : uint8_t;
enum class Linkage : uint8_t;
enum class MSInheritanceModel : uint8_t;
enum class MSVCMajorVersion : uint8_t;
enum class MSVtorDispMode : uint8_t;
enum class MethodRefFlags : uint8_t;
enum class ModifiableType : uint8_t;
enum class MultiVersionKind : uint8_t;
enum class NameKind : uint8_t;
enum class NeedExtraManglingDecl : uint8_t;
enum class NestedNameSpecifierDependence : uint8_t;
enum class NonOdrUseReason : uint8_t;
enum class NonceObjCInterface : uint8_t;
enum class NullabilityKind : uint8_t;
enum class ObjCBridgeCastKind : uint8_t;
enum class ObjCDispatchMethodKind : uint8_t;
enum class ObjCInstanceTypeFamily : uint8_t;
enum class ObjCLifetime : uint8_t;
enum class ObjCMethodFamily : uint8_t;
enum class ObjCPropertyQueryKind : uint8_t;
enum class ObjCStringFormatFamily : uint8_t;
enum class ObjCSubstitutionContext : uint8_t;
enum class ObjCTypeParamVariance : uint8_t;
enum class OnOffSwitch : uint8_t;
enum class OnStackType : uint8_t;
enum class OpenMPAdjustArgsOpKind : uint8_t;
enum class OpenMPAtClauseKind : uint8_t;
enum class OpenMPAtomicDefaultMemOrderClauseKind : uint8_t;
enum class OpenMPBindClauseKind : uint8_t;
enum class OpenMPDefaultmapClauseKind : uint8_t;
enum class OpenMPDefaultmapClauseModifier : uint8_t;
enum class OpenMPDependClauseKind : uint8_t;
enum class OpenMPDeviceClauseModifier : uint8_t;
enum class OpenMPDeviceType : uint8_t;
enum class OpenMPDistScheduleClauseKind : uint8_t;
enum class OpenMPDoacrossClauseModifier : uint8_t;
enum class OpenMPGrainsizeClauseModifier : uint8_t;
enum class OpenMPLastprivateModifier : uint8_t;
enum class OpenMPLinearClauseKind : uint8_t;
enum class OpenMPMapClauseKind : uint8_t;
enum class OpenMPMapModifierKind : uint8_t;
enum class OpenMPMotionModifierKind : uint8_t;
enum class OpenMPNumTasksClauseModifier : uint8_t;
enum class OpenMPOrderClauseKind : uint8_t;
enum class OpenMPOrderClauseModifier : uint8_t;
enum class OpenMPReductionClauseModifier : uint8_t;
enum class OpenMPScheduleClauseKind : uint8_t;
enum class OpenMPScheduleClauseModifier : uint8_t;
enum class OpenMPSeverityClauseKind : uint8_t;
enum class OverloadedOperatorKind : uint8_t;
enum class OverloadsShown : uint8_t;
enum class ParameterABI : uint8_t;
enum class ParenLocsOffsets : uint8_t;
enum class PragmaFloatControlKind : uint8_t;
enum class PragmaMSCommentKind : uint8_t;
enum class PragmaMSPointersToMembersKind : uint8_t;
enum class PragmaMSStructKind : uint8_t;
enum class PragmaSectionFlag : uint8_t;
enum class ProfileInstrKind : uint8_t;
enum class Qualified : uint8_t;
enum class RangeExprOffset : uint8_t;
enum class RangeLocOffset : uint8_t;
enum class RefQualifierKind : uint8_t;
enum class RemarkKind : uint8_t;
enum class ReservedIdentifierStatus : uint8_t;
enum class ReservedLiteralSuffixIdStatus : uint8_t;
enum class SFINAEResponse : uint8_t;
enum class SYCLMajorVersion : uint8_t;
enum class SanitizerOrdinal : uint8_t;
enum class SelectorLocationsKind : uint8_t;
enum class ShaderStage : uint8_t;
enum class SignReturnAddressKeyKind : uint8_t;
enum class SignReturnAddressScopeKind : uint8_t;
enum class SignedOverflowBehaviorTy : uint8_t;
enum class SpecialMemberFlags : uint8_t;
enum class SpecifierKind : uint8_t;
enum class StackProtectorMode : uint8_t;
enum class StorageClass : uint8_t;
enum class StorageDuration : uint8_t;
enum class StoredNameKind : uint8_t;
enum class StoredSpecifierKind : uint8_t;
enum class StrictFlexArraysLevelKind : uint8_t;
enum class StructReturnConventionKind : uint8_t;
enum class SubExpr : uint8_t;
enum class SubStmt : uint8_t;
enum class SwiftAsyncFramePointerKind : uint8_t;
enum class SyncScope : uint8_t;
enum class Syntax : uint8_t;
enum class TLSModel : uint8_t;
enum class TQ : uint8_t;
enum class TagTypeKind : uint8_t;
enum class TailPaddingUseRules : uint8_t;
enum class TemplateArgumentDependence : uint8_t;
enum class TemplateNameDependence : uint8_t;
enum class TemplateSpecializationKind : uint8_t;
enum class TextDiagnosticFormat : uint8_t;
enum class ThreadModelKind : uint8_t;
enum class ThreadStorageClassSpecifier : uint8_t;
enum class TrailingAllocKind : uint8_t;
enum class TranslationUnitKind : uint8_t;
enum class TrivialAutoVarInitKind : uint8_t;
enum class TypeDependence : uint8_t;
enum class TypeLocClass : uint8_t;
enum class TypeOfKind : uint8_t;
enum class TypeSpecifierSign : uint8_t;
enum class TypeSpecifierType : uint8_t;
enum class TypeSpecifierWidth : uint8_t;
enum class TypeSpecifiersPipe : uint8_t;
enum class TypeTrait : uint8_t;
enum class UnaryExprOrTypeTrait : uint8_t;
enum class UnaryOperatorKind : uint8_t;
enum class APValueKind : uint8_t;
enum class VectorLibrary : uint8_t;
enum class Visibility : uint8_t;
enum class AttributeSyntax : uint8_t;
enum class DeclCategory : uint8_t;
enum class PseudoKind : uint8_t;
enum class EntityCategory : int32_t;
class TokenContext;
class Designator;
class CXXBaseSpecifier;
class TemplateParameterList;
class TemplateArgument;
class Attr;
class AlignValueAttr;
class AliasAttr;
class AbiTagAttr;
class TypeAttr;
class SPtrAttr;
class Ptr64Attr;
class Ptr32Attr;
class OpenCLPrivateAddressSpaceAttr;
class OpenCLLocalAddressSpaceAttr;
class OpenCLGlobalHostAddressSpaceAttr;
class OpenCLGlobalDeviceAddressSpaceAttr;
class OpenCLGlobalAddressSpaceAttr;
class OpenCLGenericAddressSpaceAttr;
class OpenCLConstantAddressSpaceAttr;
class ObjCKindOfAttr;
class ObjCInertUnsafeUnretainedAttr;
class ObjCGCAttr;
class NoDerefAttr;
class HLSLGroupSharedAddressSpaceAttr;
class CmseNSCallAttr;
class BTFTypeTagAttr;
class ArmStreamingAttr;
class ArmMveStrictPolymorphismAttr;
class AnnotateTypeAttr;
class AddressSpaceAttr;
class WebAssemblyFuncrefAttr;
class UPtrAttr;
class TypeNullableResultAttr;
class TypeNullableAttr;
class TypeNullUnspecifiedAttr;
class TypeNonNullAttr;
class ThreadAttr;
class SwiftObjCMembersAttr;
class StmtAttr;
class OpenCLUnrollHintAttr;
class MustTailAttr;
class LikelyAttr;
class FallThroughAttr;
class UnlikelyAttr;
class SuppressAttr;
class RenderScriptKernelAttr;
class OverloadableAttr;
class OpenCLAccessAttr;
class ObjCRuntimeVisibleAttr;
class ObjCRuntimeNameAttr;
class ObjCNonRuntimeProtocolAttr;
class ObjCNonLazyClassAttr;
class ObjCDirectMembersAttr;
class ObjCDirectAttr;
class ObjCDesignatedInitializerAttr;
class ObjCClassStubAttr;
class ObjCBoxableAttr;
class OMPReferencedVarAttr;
class OMPDeclareSimdDeclAttr;
class OMPCaptureKindAttr;
class NoEscapeAttr;
class NoBuiltinAttr;
class ModeAttr;
class LoopHintAttr;
class LoaderUninitializedAttr;
class InitSegAttr;
class InheritableAttr;
class IBOutletCollectionAttr;
class IBOutletAttr;
class IBActionAttr;
class HotAttr;
class HLSLShaderAttr;
class HLSLResourceBindingAttr;
class HLSLResourceAttr;
class HLSLNumThreadsAttr;
class HLSLAnnotationAttr;
class HLSLSV_GroupIndexAttr;
class HLSLSV_DispatchThreadIDAttr;
class HIPManagedAttr;
class GuardedVarAttr;
class GuardedByAttr;
class GNUInlineAttr;
class FunctionReturnThunksAttr;
class FormatAttr;
class FormatArgAttr;
class FlattenAttr;
class FlagEnumAttr;
class FinalAttr;
class FastCallAttr;
class ExternalSourceSymbolAttr;
class ExclusiveTrylockFunctionAttr;
class ExcludeFromExplicitInstantiationAttr;
class ErrorAttr;
class EnumExtensibilityAttr;
class EnforceTCBLeafAttr;
class EnforceTCBAttr;
class EnableIfAttr;
class EmptyBasesAttr;
class DisableTailCallsAttr;
class DisableSanitizerInstrumentationAttr;
class DiagnoseIfAttr;
class DiagnoseAsBuiltinAttr;
class DestructorAttr;
class DeprecatedAttr;
class DeclOrStmtAttr;
class AlwaysInlineAttr;
class NoMergeAttr;
class NoInlineAttr;
class DLLImportStaticLocalAttr;
class DLLImportAttr;
class DLLExportStaticLocalAttr;
class DLLExportAttr;
class ConvergentAttr;
class ConsumableSetOnReadAttr;
class ConsumableAutoCastAttr;
class ConsumableAttr;
class ConstructorAttr;
class ConstInitAttr;
class ConstAttr;
class CommonAttr;
class ColdAttr;
class CodeSegAttr;
class CmseNSEntryAttr;
class CleanupAttr;
class CapturedRecordAttr;
class CapabilityAttr;
class CallbackAttr;
class CallableWhenAttr;
class CXX11NoReturnAttr;
class CUDASharedAttr;
class CUDALaunchBoundsAttr;
class CUDAInvalidTargetAttr;
class CUDAHostAttr;
class CUDAGlobalAttr;
class CUDADeviceBuiltinTextureTypeAttr;
class CUDADeviceBuiltinSurfaceTypeAttr;
class CUDADeviceAttr;
class CUDAConstantAttr;
class CPUSpecificAttr;
class CPUDispatchAttr;
class CFUnknownTransferAttr;
class CFReturnsRetainedAttr;
class CFReturnsNotRetainedAttr;
class CFICanonicalJumpTableAttr;
class CFGuardAttr;
class CFAuditedTransferAttr;
class CDeclAttr;
class C11NoReturnAttr;
class BuiltinAttr;
class BlocksAttr;
class BTFDeclTagAttr;
class BPFPreserveAccessIndexAttr;
class AvailableOnlyInDefaultEvalMethodAttr;
class AvailabilityAttr;
class AssumptionAttr;
class AssumeAlignedAttr;
class AssertSharedLockAttr;
class AssertExclusiveLockAttr;
class AssertCapabilityAttr;
class AsmLabelAttr;
class ArtificialAttr;
class ArmBuiltinAliasAttr;
class ArgumentWithTypeTagAttr;
class ArcWeakrefUnavailableAttr;
class AnyX86NoCfCheckAttr;
class AnyX86NoCallerSavedRegistersAttr;
class AnyX86InterruptAttr;
class AnalyzerNoReturnAttr;
class AlwaysDestroyAttr;
class AllocSizeAttr;
class AllocAlignAttr;
class AlignedAttr;
class AlignNaturalAttr;
class AlignMac68kAttr;
class AcquiredBeforeAttr;
class AcquiredAfterAttr;
class AcquireHandleAttr;
class AcquireCapabilityAttr;
class AVRSignalAttr;
class AVRInterruptAttr;
class ARMInterruptAttr;
class AMDGPUWavesPerEUAttr;
class AMDGPUNumVGPRAttr;
class AMDGPUNumSGPRAttr;
class AMDGPUKernelCallAttr;
class AMDGPUFlatWorkGroupSizeAttr;
class AArch64VectorPcsAttr;
class AArch64SVEPcsAttr;
class ZeroCallUsedRegsAttr;
class XRayLogArgsAttr;
class XRayInstrumentAttr;
class X86ForceAlignArgPointerAttr;
class WorkGroupSizeHintAttr;
class WebAssemblyImportNameAttr;
class WebAssemblyImportModuleAttr;
class WebAssemblyExportNameAttr;
class WeakRefAttr;
class WeakImportAttr;
class WeakAttr;
class WarnUnusedResultAttr;
class WarnUnusedAttr;
class VisibilityAttr;
class VectorCallAttr;
class VecTypeHintAttr;
class VecReturnAttr;
class UuidAttr;
class UsingIfExistsAttr;
class UsedAttr;
class UnusedAttr;
class UnsafeBufferUsageAttr;
class UninitializedAttr;
class UnavailableAttr;
class TypeVisibilityAttr;
class TypeTagForDatatypeAttr;
class TryAcquireCapabilityAttr;
class TrivialABIAttr;
class TransparentUnionAttr;
class ThisCallAttr;
class TestTypestateAttr;
class TargetVersionAttr;
class TargetClonesAttr;
class TargetAttr;
class TLSModelAttr;
class SysVABIAttr;
class SwiftPrivateAttr;
class SwiftNewTypeAttr;
class SwiftNameAttr;
class SwiftErrorAttr;
class SwiftCallAttr;
class SwiftBridgedTypedefAttr;
class SwiftBridgeAttr;
class SwiftAttrAttr;
class SwiftAsyncNameAttr;
class SwiftAsyncErrorAttr;
class SwiftAsyncCallAttr;
class SwiftAsyncAttr;
class StrictGuardStackCheckAttr;
class StrictFPAttr;
class StdCallAttr;
class StandaloneDebugAttr;
class SpeculativeLoadHardeningAttr;
class SharedTrylockFunctionAttr;
class SetTypestateAttr;
class SentinelAttr;
class SelectAnyAttr;
class SectionAttr;
class ScopedLockableAttr;
class SYCLSpecialClassAttr;
class SYCLKernelAttr;
class ReturnsTwiceAttr;
class ReturnsNonNullAttr;
class ReturnTypestateAttr;
class RetainAttr;
class RestrictAttr;
class RequiresCapabilityAttr;
class ReqdWorkGroupSizeAttr;
class ReleaseCapabilityAttr;
class ReinitializesAttr;
class RegCallAttr;
class ReadOnlyPlacementAttr;
class RandomizeLayoutAttr;
class RISCVInterruptAttr;
class PureAttr;
class PtGuardedVarAttr;
class PtGuardedByAttr;
class PreserveMostAttr;
class PreserveAllAttr;
class PreferredNameAttr;
class PragmaClangTextSectionAttr;
class PragmaClangRodataSectionAttr;
class PragmaClangRelroSectionAttr;
class PragmaClangDataSectionAttr;
class PragmaClangBSSSectionAttr;
class PointerAttr;
class PcsAttr;
class PatchableFunctionEntryAttr;
class PascalAttr;
class ParamTypestateAttr;
class PackedAttr;
class OwnershipAttr;
class OwnerAttr;
class OverrideAttr;
class OptimizeNoneAttr;
class OpenCLKernelAttr;
class OpenCLIntelReqdSubGroupSizeAttr;
class ObjCSubclassingRestrictedAttr;
class ObjCRootClassAttr;
class ObjCReturnsInnerPointerAttr;
class ObjCRequiresSuperAttr;
class ObjCRequiresPropertyDefsAttr;
class ObjCPreciseLifetimeAttr;
class ObjCOwnershipAttr;
class ObjCNSObjectAttr;
class ObjCMethodFamilyAttr;
class ObjCIndependentClassAttr;
class ObjCExternallyRetainedAttr;
class ObjCExplicitProtocolImplAttr;
class ObjCExceptionAttr;
class ObjCBridgeRelatedAttr;
class ObjCBridgeMutableAttr;
class ObjCBridgeAttr;
class OSReturnsRetainedOnZeroAttr;
class OSReturnsRetainedOnNonZeroAttr;
class OSReturnsRetainedAttr;
class OSReturnsNotRetainedAttr;
class OSConsumesThisAttr;
class OMPThreadPrivateDeclAttr;
class OMPDeclareVariantAttr;
class OMPDeclareTargetDeclAttr;
class OMPCaptureNoInitAttr;
class OMPAllocateDeclAttr;
class NotTailCalledAttr;
class NoUwtableAttr;
class NoUniqueAddressAttr;
class NoThrowAttr;
class NoThreadSafetyAnalysisAttr;
class NoStackProtectorAttr;
class NoSplitStackAttr;
class NoSpeculativeLoadHardeningAttr;
class NoSanitizeAttr;
class NoReturnAttr;
class NoRandomizeLayoutAttr;
class NoProfileFunctionAttr;
class NoMips16Attr;
class NoMicroMipsAttr;
class NoInstrumentFunctionAttr;
class NoDuplicateAttr;
class NoDestroyAttr;
class NoDebugAttr;
class NoCommonAttr;
class NoAliasAttr;
class NakedAttr;
class NVPTXKernelAttr;
class NSReturnsRetainedAttr;
class NSReturnsNotRetainedAttr;
class NSReturnsAutoreleasedAttr;
class NSErrorDomainAttr;
class NSConsumesSelfAttr;
class MipsShortCallAttr;
class MipsLongCallAttr;
class MipsInterruptAttr;
class Mips16Attr;
class MinVectorWidthAttr;
class MinSizeAttr;
class MicroMipsAttr;
class MaybeUndefAttr;
class MayAliasAttr;
class MaxFieldAlignmentAttr;
class MSVtorDispAttr;
class MSStructAttr;
class MSP430InterruptAttr;
class MSNoVTableAttr;
class MSInheritanceAttr;
class MSAllocatorAttr;
class MSABIAttr;
class MIGServerRoutineAttr;
class M68kInterruptAttr;
class LocksExcludedAttr;
class LockReturnedAttr;
class LifetimeBoundAttr;
class LeafAttr;
class LayoutVersionAttr;
class LTOVisibilityPublicAttr;
class InternalLinkageAttr;
class IntelOclBiccAttr;
class InitPriorityAttr;
class InheritableParamAttr;
class CarriesDependencyAttr;
class CFConsumedAttr;
class AnnotateAttr;
class UseHandleAttr;
class ReleaseHandleAttr;
class PassObjectSizeAttr;
class ParameterABIAttr;
class SwiftIndirectResultAttr;
class SwiftErrorResultAttr;
class SwiftContextAttr;
class SwiftAsyncContextAttr;
class OSConsumedAttr;
class NonNullAttr;
class NSConsumedAttr;
class IFuncAttr;
class CalledOnceAttr;
class BuiltinAliasAttr;
class Type;
class TemplateTypeParmType;
class TemplateSpecializationType;
class TagType;
class RecordType;
class EnumType;
class SubstTemplateTypeParmType;
class SubstTemplateTypeParmPackType;
class ReferenceType;
class RValueReferenceType;
class LValueReferenceType;
class QualifiedType;
class PointerType;
class PipeType;
class ParenType;
class PackExpansionType;
class ObjCTypeParamType;
class ObjCObjectType;
class ObjCInterfaceType;
class ObjCObjectPointerType;
class MemberPointerType;
class MatrixType;
class DependentSizedMatrixType;
class ConstantMatrixType;
class MacroQualifiedType;
class InjectedClassNameType;
class FunctionType;
class FunctionProtoType;
class FunctionNoProtoType;
class DependentVectorType;
class DependentSizedExtVectorType;
class DependentBitIntType;
class DependentAddressSpaceType;
class DeducedType;
class DeducedTemplateSpecializationType;
class AutoType;
class DecltypeType;
class ComplexType;
class BuiltinType;
class BlockPointerType;
class BitIntType;
class BTFTagAttributedType;
class AttributedType;
class AtomicType;
class ArrayType;
class VariableArrayType;
class IncompleteArrayType;
class DependentSizedArrayType;
class ConstantArrayType;
class AdjustedType;
class DecayedType;
class TypeWithKeyword;
class ElaboratedType;
class DependentTemplateSpecializationType;
class DependentNameType;
class VectorType;
class ExtVectorType;
class UsingType;
class UnresolvedUsingType;
class UnaryTransformType;
class TypedefType;
class TypeOfType;
class TypeOfExprType;
class Stmt;
class SEHTryStmt;
class SEHLeaveStmt;
class SEHFinallyStmt;
class SEHExceptStmt;
class ReturnStmt;
class ObjCForCollectionStmt;
class ObjCAutoreleasePoolStmt;
class ObjCAtTryStmt;
class ObjCAtThrowStmt;
class ObjCAtSynchronizedStmt;
class ObjCAtFinallyStmt;
class ObjCAtCatchStmt;
class OMPExecutableDirective;
class OMPErrorDirective;
class OMPDispatchDirective;
class OMPDepobjDirective;
class OMPCriticalDirective;
class OMPCancellationPointDirective;
class OMPCancelDirective;
class OMPBarrierDirective;
class OMPAtomicDirective;
class OMPTeamsDirective;
class OMPTaskyieldDirective;
class OMPTaskwaitDirective;
class OMPTaskgroupDirective;
class OMPTaskDirective;
class OMPTargetUpdateDirective;
class OMPTargetTeamsDirective;
class OMPTargetParallelDirective;
class OMPTargetExitDataDirective;
class OMPTargetEnterDataDirective;
class OMPTargetDirective;
class OMPTargetDataDirective;
class OMPSingleDirective;
class OMPSectionsDirective;
class OMPSectionDirective;
class OMPScanDirective;
class OMPParallelSectionsDirective;
class OMPParallelMasterDirective;
class OMPParallelMaskedDirective;
class OMPParallelDirective;
class OMPOrderedDirective;
class OMPMetaDirective;
class OMPMasterDirective;
class OMPMaskedDirective;
class OMPLoopBasedDirective;
class OMPLoopTransformationDirective;
class OMPUnrollDirective;
class OMPTileDirective;
class OMPLoopDirective;
class OMPGenericLoopDirective;
class OMPForSimdDirective;
class OMPForDirective;
class OMPDistributeSimdDirective;
class OMPDistributeParallelForSimdDirective;
class OMPDistributeParallelForDirective;
class OMPDistributeDirective;
class OMPTeamsGenericLoopDirective;
class OMPTeamsDistributeSimdDirective;
class OMPTeamsDistributeParallelForSimdDirective;
class OMPTeamsDistributeParallelForDirective;
class OMPTeamsDistributeDirective;
class OMPTaskLoopSimdDirective;
class OMPTaskLoopDirective;
class OMPTargetTeamsGenericLoopDirective;
class OMPTargetTeamsDistributeSimdDirective;
class OMPTargetTeamsDistributeParallelForSimdDirective;
class OMPTargetTeamsDistributeParallelForDirective;
class OMPTargetTeamsDistributeDirective;
class OMPTargetSimdDirective;
class OMPTargetParallelGenericLoopDirective;
class OMPTargetParallelForSimdDirective;
class OMPTargetParallelForDirective;
class OMPSimdDirective;
class OMPParallelMasterTaskLoopSimdDirective;
class OMPParallelMasterTaskLoopDirective;
class OMPParallelMaskedTaskLoopSimdDirective;
class OMPParallelMaskedTaskLoopDirective;
class OMPParallelGenericLoopDirective;
class OMPParallelForSimdDirective;
class OMPParallelForDirective;
class OMPMasterTaskLoopSimdDirective;
class OMPMasterTaskLoopDirective;
class OMPMaskedTaskLoopSimdDirective;
class OMPMaskedTaskLoopDirective;
class OMPInteropDirective;
class OMPFlushDirective;
class OMPCanonicalLoop;
class NullStmt;
class MSDependentExistsStmt;
class IndirectGotoStmt;
class IfStmt;
class GotoStmt;
class ForStmt;
class DoStmt;
class DeclStmt;
class CoroutineBodyStmt;
class CoreturnStmt;
class ContinueStmt;
class CompoundStmt;
class CapturedStmt;
class CXXTryStmt;
class CXXForRangeStmt;
class CXXCatchStmt;
class BreakStmt;
class AsmStmt;
class MSAsmStmt;
class GCCAsmStmt;
class WhileStmt;
class ValueStmt;
class LabelStmt;
class Expr;
class DesignatedInitUpdateExpr;
class DesignatedInitExpr;
class DependentScopeDeclRefExpr;
class DependentCoawaitExpr;
class DeclRefExpr;
class CoroutineSuspendExpr;
class CoawaitExpr;
class CoyieldExpr;
class ConvertVectorExpr;
class ConceptSpecializationExpr;
class CompoundLiteralExpr;
class ChooseExpr;
class CharacterLiteral;
class CastExpr;
class ImplicitCastExpr;
class ExplicitCastExpr;
class CXXNamedCastExpr;
class CXXDynamicCastExpr;
class CXXConstCastExpr;
class CXXAddrspaceCastExpr;
class CXXStaticCastExpr;
class CXXReinterpretCastExpr;
class CXXFunctionalCastExpr;
class CStyleCastExpr;
class BuiltinBitCastExpr;
class ObjCBridgedCastExpr;
class CallExpr;
class CXXOperatorCallExpr;
class CXXMemberCallExpr;
class CUDAKernelCallExpr;
class UserDefinedLiteral;
class CXXUuidofExpr;
class CXXUnresolvedConstructExpr;
class CXXTypeidExpr;
class CXXThrowExpr;
class CXXThisExpr;
class CXXStdInitializerListExpr;
class CXXScalarValueInitExpr;
class CXXRewrittenBinaryOperator;
class CXXPseudoDestructorExpr;
class CXXParenListInitExpr;
class CXXNullPtrLiteralExpr;
class CXXNoexceptExpr;
class CXXNewExpr;
class CXXInheritedCtorInitExpr;
class CXXFoldExpr;
class CXXDependentScopeMemberExpr;
class CXXDeleteExpr;
class CXXDefaultInitExpr;
class CXXDefaultArgExpr;
class CXXConstructExpr;
class CXXTemporaryObjectExpr;
class CXXBoolLiteralExpr;
class CXXBindTemporaryExpr;
class BlockExpr;
class BinaryOperator;
class CompoundAssignOperator;
class AtomicExpr;
class AsTypeExpr;
class ArrayTypeTraitExpr;
class ArraySubscriptExpr;
class ArrayInitLoopExpr;
class ArrayInitIndexExpr;
class AddrLabelExpr;
class AbstractConditionalOperator;
class ConditionalOperator;
class BinaryConditionalOperator;
class VAArgExpr;
class UnaryOperator;
class UnaryExprOrTypeTraitExpr;
class TypoExpr;
class TypeTraitExpr;
class SubstNonTypeTemplateParmPackExpr;
class SubstNonTypeTemplateParmExpr;
class StringLiteral;
class StmtExpr;
class SourceLocExpr;
class SizeOfPackExpr;
class ShuffleVectorExpr;
class SYCLUniqueStableNameExpr;
class RequiresExpr;
class RecoveryExpr;
class PseudoObjectExpr;
class PredefinedExpr;
class ParenListExpr;
class ParenExpr;
class PackExpansionExpr;
class OverloadExpr;
class UnresolvedMemberExpr;
class UnresolvedLookupExpr;
class OpaqueValueExpr;
class OffsetOfExpr;
class ObjCSubscriptRefExpr;
class ObjCStringLiteral;
class ObjCSelectorExpr;
class ObjCProtocolExpr;
class ObjCPropertyRefExpr;
class ObjCMessageExpr;
class ObjCIvarRefExpr;
class ObjCIsaExpr;
class ObjCIndirectCopyRestoreExpr;
class ObjCEncodeExpr;
class ObjCDictionaryLiteral;
class ObjCBoxedExpr;
class ObjCBoolLiteralExpr;
class ObjCAvailabilityCheckExpr;
class ObjCArrayLiteral;
class OMPIteratorExpr;
class OMPArrayShapingExpr;
class OMPArraySectionExpr;
class NoInitExpr;
class MemberExpr;
class MatrixSubscriptExpr;
class MaterializeTemporaryExpr;
class MSPropertySubscriptExpr;
class MSPropertyRefExpr;
class LambdaExpr;
class IntegerLiteral;
class InitListExpr;
class ImplicitValueInitExpr;
class ImaginaryLiteral;
class GenericSelectionExpr;
class GNUNullExpr;
class FunctionParmPackExpr;
class FullExpr;
class ExprWithCleanups;
class ConstantExpr;
class FloatingLiteral;
class FixedPointLiteral;
class ExtVectorElementExpr;
class ExpressionTraitExpr;
class AttributedStmt;
class SwitchStmt;
class SwitchCase;
class DefaultStmt;
class CaseStmt;
class Decl;
class ClassScopeFunctionSpecializationDecl;
class CapturedDecl;
class BlockDecl;
class AccessSpecDecl;
class OMPDeclarativeDirectiveDecl;
class OMPThreadPrivateDecl;
class OMPRequiresDecl;
class OMPAllocateDecl;
class TranslationUnitDecl;
class TopLevelStmtDecl;
class StaticAssertDecl;
class RequiresExprBodyDecl;
class PragmaDetectMismatchDecl;
class PragmaCommentDecl;
class ObjCPropertyImplDecl;
class NamedDecl;
class LabelDecl;
class HLSLBufferDecl;
class BaseUsingDecl;
class UsingEnumDecl;
class UsingDecl;
class ValueDecl;
class UnresolvedUsingValueDecl;
class UnnamedGlobalConstantDecl;
class TemplateParamObjectDecl;
class OMPDeclareReductionDecl;
class MSGuidDecl;
class IndirectFieldDecl;
class EnumConstantDecl;
class DeclaratorDecl;
class VarDecl;
class ParmVarDecl;
class OMPCapturedExprDecl;
class ImplicitParamDecl;
class DecompositionDecl;
class VarTemplateSpecializationDecl;
class VarTemplatePartialSpecializationDecl;
class NonTypeTemplateParmDecl;
class MSPropertyDecl;
class FunctionDecl;
class CXXMethodDecl;
class CXXDestructorDecl;
class CXXConversionDecl;
class CXXConstructorDecl;
class CXXDeductionGuideDecl;
class FieldDecl;
class ObjCIvarDecl;
class ObjCAtDefsFieldDecl;
class BindingDecl;
class OMPDeclarativeDirectiveValueDecl;
class OMPDeclareMapperDecl;
class UsingShadowDecl;
class ConstructorUsingShadowDecl;
class UsingPackDecl;
class UsingDirectiveDecl;
class UnresolvedUsingIfExistsDecl;
class TypeDecl;
class TemplateTypeParmDecl;
class TagDecl;
class RecordDecl;
class CXXRecordDecl;
class ClassTemplateSpecializationDecl;
class ClassTemplatePartialSpecializationDecl;
class EnumDecl;
class UnresolvedUsingTypenameDecl;
class TypedefNameDecl;
class TypedefDecl;
class TypeAliasDecl;
class ObjCTypeParamDecl;
class TemplateDecl;
class RedeclarableTemplateDecl;
class FunctionTemplateDecl;
class ClassTemplateDecl;
class VarTemplateDecl;
class TypeAliasTemplateDecl;
class ConceptDecl;
class BuiltinTemplateDecl;
class TemplateTemplateParmDecl;
class ObjCPropertyDecl;
class ObjCMethodDecl;
class ObjCContainerDecl;
class ObjCCategoryDecl;
class ObjCProtocolDecl;
class ObjCInterfaceDecl;
class ObjCImplDecl;
class ObjCCategoryImplDecl;
class ObjCImplementationDecl;
class ObjCCompatibleAliasDecl;
class NamespaceDecl;
class NamespaceAliasDecl;
class LinkageSpecDecl;
class LifetimeExtendedTemporaryDecl;
class ImportDecl;
class ImplicitConceptSpecializationDecl;
class FriendTemplateDecl;
class FriendDecl;
class FileScopeAsmDecl;
class ExternCContextDecl;
class ExportDecl;
class EmptyDecl;
class Compilation;
enum class BuiltinReferenceKind : int32_t;
class ReferenceKind;
class Reference;
class Token;
class TokenRange;
class File;
class TokenTreeVisitor;
class TokenTree;
enum class TokenKind : uint16_t;
enum class MacroKind : uint8_t;
enum class PathKind : uint8_t;
enum class FileType : uint8_t;
enum class CompilerName : uint8_t;
enum class IncludePathLocation : uint8_t;
enum class TargetLanguage : uint8_t;
enum class TokenCategory : uint8_t;
class Macro;
class MacroVAOptArgument;
class MacroVAOpt;
class MacroSubstitution;
class MacroConcatenate;
class MacroStringify;
class MacroExpansion;
class MacroParameterSubstitution;
class MacroArgument;
class MacroParameter;
class MacroDirective;
class DefineMacroDirective;
class PragmaMacroDirective;
class UndefineMacroDirective;
class OtherMacroDirective;
class ConditionalMacroDirective;
class EndIfMacroDirective;
class ElseMacroDirective;
class ElseIfNotDefinedMacroDirective;
class ElseIfDefinedMacroDirective;
class ElseIfMacroDirective;
class IfNotDefinedMacroDirective;
class IfDefinedMacroDirective;
class IfMacroDirective;
class IncludeLikeMacroDirective;
class ImportMacroDirective;
class IncludeMacrosMacroDirective;
class IncludeNextMacroDirective;
class IncludeMacroDirective;
class Fragment;
class RegexQueryMatch;
enum class IndexStatus : uint32_t;
class Index;
namespace ir {
enum class AttributeKind : uint32_t;
class Attribute;
class Value;
class Block;
class Argument;
class Label;
enum class OperationKind : uint32_t;
class Operation;
class Result;
class Operand;
enum BasicBlockOrder : int32_t;
class Region;
enum class TypeKind : uint32_t;
class Type;
}  // namespace ir
namespace ir::builtin {
class ElementsAttr;
class ArrayAttr;
class DenseArrayAttr;
class DictionaryAttr;
class FloatAttr;
class IntegerAttr;
class OpaqueAttr;
class StringAttr;
class StridedLayoutAttr;
class BoolAttr;
class ShapedType;
class IntegerType;
class OpaqueType;
class VectorType;
class ModuleOp;
class UnrealizedConversionCastOp;
}  // namespace ir::builtin
namespace ir::llvm {
class DIBasicTypeAttr;
class DICompileUnitAttr;
class DICompositeTypeAttr;
class DIDerivedTypeAttr;
class DINamespaceAttr;
class MemoryEffectsAttr;
class TBAAMemberAttr;
class TBAATagAttr;
class TBAATypeDescriptorAttr;
class FunctionType;
class PointerType;
class TargetExtType;
class AShrOp;
class AddOp;
class AddrSpaceCastOp;
class AddressOfOp;
class AllocaOp;
class AndOp;
class AtomicCmpXchgOp;
class AtomicRMWOp;
class BitcastOp;
class BrOp;
class CallOp;
class ComdatOp;
class ComdatSelectorOp;
class CondBrOp;
class ConstantOp;
class ExtractElementOp;
class ExtractValueOp;
class FAddOp;
class FCmpOp;
class FDivOp;
class FMulOp;
class FNegOp;
class FPExtOp;
class FPToSIOp;
class FPToUIOp;
class FPTruncOp;
class FRemOp;
class FSubOp;
class FenceOp;
class FreezeOp;
class GetElementPtrOp;
class GlobalOp;
class ICmpOp;
class InlineAsmOp;
class InsertElementOp;
class InsertValueOp;
class IntToPtrOp;
class InvokeOp;
class FuncOp;
class LShrOp;
class LandingpadOp;
class LoadOp;
class MetadataOp;
class MulOp;
class OrOp;
class PoisonOp;
class PtrToIntOp;
class ResumeOp;
class ReturnOp;
class SDivOp;
class SExtOp;
class SIToFPOp;
class SRemOp;
class SelectOp;
class ShlOp;
class ShuffleVectorOp;
class StoreOp;
class SubOp;
class SwitchOp;
class TruncOp;
class UDivOp;
class UIToFPOp;
class URemOp;
class UndefOp;
class XOrOp;
class ZExtOp;
class AbsOp;
class BitReverseOp;
class ByteSwapOp;
class CallIntrinsicOp;
class CopySignOp;
class CoroAlignOp;
class CoroBeginOp;
class CoroEndOp;
class CoroFreeOp;
class CoroIdOp;
class CoroResumeOp;
class CoroSaveOp;
class CoroSizeOp;
class CoroSuspendOp;
class CosOp;
class CountLeadingZerosOp;
class CountTrailingZerosOp;
class CtPopOp;
class DbgValueOp;
class EhTypeidForOp;
class Exp2Op;
class ExpOp;
class ExpectOp;
class ExpectWithProbabilityOp;
class FAbsOp;
class FCeilOp;
class FFloorOp;
class FMAOp;
class FMulAddOp;
class FTruncOp;
class FShlOp;
class FShrOp;
class GetActiveLaneMaskOp;
class IsConstantOp;
class IsFPClassOp;
class LifetimeEndOp;
class LifetimeStartOp;
class RoundAndCastToLongLongOp;
class RoundAndCastToNearestLongLongOp;
class Log10Op;
class Log2Op;
class LogOp;
class RoundAndCastToLongOp;
class RoundAndCastToNearestLongOp;
class MaskedLoadOp;
class MaskedStoreOp;
class MatrixColumnMajorLoadOp;
class MatrixColumnMajorStoreOp;
class MatrixMultiplyOp;
class MatrixTransposeOp;
class MaxNumOp;
class MaximumOp;
class MemcpyInlineOp;
class MemcpyOp;
class MemmoveOp;
class MemsetOp;
class MinNumOp;
class MinimumOp;
class RoundToNearbyIntOp;
class PowIOp;
class FPowOp;
class PrefetchOp;
class RoundToIntOp;
class RoundToNearestEvenOp;
class RoundToNearestOp;
class SAddSatOp;
class SAddWithOverflowOp;
class SMaxOp;
class SMinOp;
class SMulWithOverflowOp;
class SSACopyOp;
class SShlSatOp;
class SSubSatOp;
class SSubWithOverflowOp;
class SinOp;
class SqrtOp;
class StackRestoreOp;
class StackSaveOp;
class StepVectorOp;
class ThreadLocalAddressOp;
class UAddSatOp;
class UAddWithOverflowOp;
class UBSanTrapOp;
class UMaxOp;
class UMinOp;
class UMulWithOverflowOp;
class UShlSatOp;
class USubSatOp;
class USubWithOverflowOp;
class VPAShrOp;
class VPAddOp;
class VPAndOp;
class VPFAddOp;
class VPFDivOp;
class VPFMulAddOp;
class VPFMulOp;
class VPFNegOp;
class VPFPExtOp;
class VPFPToSIOp;
class VPFPToUIOp;
class VPFPTruncOp;
class VPFRemOp;
class VPFSubOp;
class VPFmaOp;
class VPIntToPtrOp;
class VPLShrOp;
class VPLoadOp;
class VPMergeMinOp;
class VPMulOp;
class VPOrOp;
class VPPtrToIntOp;
class VPReduceAddOp;
class VPReduceAndOp;
class VPReduceFAddOp;
class VPReduceFMaxOp;
class VPReduceFMinOp;
class VPReduceFMulOp;
class VPReduceMulOp;
class VPReduceOrOp;
class VPReduceSMaxOp;
class VPReduceSMinOp;
class VPReduceUMaxOp;
class VPReduceUMinOp;
class VPReduceXorOp;
class VPSDivOp;
class VPSExtOp;
class VPSIToFPOp;
class VPSRemOp;
class VPSelectMinOp;
class VPShlOp;
class VPStoreOp;
class VPStridedLoadOp;
class VPStridedStoreOp;
class VPSubOp;
class VPTruncOp;
class VPUDivOp;
class VPUIToFPOp;
class VPURemOp;
class VPXorOp;
class VPZExtOp;
class VaCopyOp;
class VaEndOp;
class VaStartOp;
class MaskedExpandLoadOp;
class MaskedGatherOp;
class MaskedScatterOp;
class VectorExtractOp;
class VectorInsertOp;
class VectorReduceAddOp;
class VectorReduceAndOp;
class VectorReduceFAddOp;
class VectorReduceFMaxOp;
class VectorReduceFMaximumOp;
class VectorReduceFMinOp;
class VectorReduceFMinimumOp;
class VectorReduceFMulOp;
class VectorReduceMulOp;
class VectorReduceOrOp;
class VectorReduceSMaxOp;
class VectorReduceSMinOp;
class VectorReduceUMaxOp;
class VectorReduceUMinOp;
class VectorReduceXorOp;
class VScaleOp;
}  // namespace ir::llvm
namespace ir::memref {
class AssumeAlignmentOp;
class AtomicRMWOp;
class AtomicYieldOp;
class GenericAtomicRMWOp;
class LoadOp;
class AllocOp;
class AllocaOp;
class AllocaScopeOp;
class AllocaScopeReturnOp;
class DimOp;
class DMAStartOp;
class DMAWaitOp;
class ExtractStridedMetadataOp;
class GetGlobalOp;
class GlobalOp;
class PrefetchOp;
class ReinterpretCastOp;
class StoreOp;
class ViewOp;
class SubViewOp;
}  // namespace ir::memref
namespace ir::abi {
class CallArgsOp;
class CallExecutionOp;
class CallOp;
class CallRetsOp;
class DirectOp;
class EpilogueOp;
class FuncOp;
class PrologueOp;
class RetDirectOp;
class TodoOp;
class WrapFuncOp;
class YieldOp;
}  // namespace ir::abi
namespace ir::ll {
class BrOp;
class ConcatOp;
class CondBrOp;
class CondScopeRetOp;
class ExtractOp;
class InitializeVarOp;
class InlineScopeOp;
class FuncOp;
class StructGEPOp;
class ReturnOp;
class ScopeOp;
class UninitializedVarOp;
}  // namespace ir::ll
namespace ir::hl {
class AllocAlignAttr;
class AllocSizeAttr;
class AsmLabelAttr;
class CVQualifiersAttr;
class CVRQualifiersAttr;
class UCVQualifiersAttr;
class EnumType;
class RecordType;
class TypeOfExprType;
class TypedefType;
class AddFAssignOp;
class AddFOp;
class AddIAssignOp;
class AddIOp;
class AddrLabelExprOp;
class AddressOfOp;
class AlignOfExprOp;
class AlignOfTypeOp;
class AssignOp;
class BinAShrAssignOp;
class BinAShrOp;
class BinAndAssignOp;
class BinAndOp;
class BinCommaOp;
class BinLAndOp;
class BinLOrOp;
class BinLShrAssignOp;
class BinLShrOp;
class BinOrAssignOp;
class BinOrOp;
class BinShlAssignOp;
class BinShlOp;
class BinXorAssignOp;
class BinXorOp;
class BuiltinBitCastOp;
class CStyleCastOp;
class CallOp;
class ClassDeclOp;
class CmpOp;
class ConstantOp;
class CxxBaseSpecifierOp;
class CxxStructDeclOp;
class DeclRefOp;
class DerefOp;
class DivFAssignOp;
class DivFOp;
class DivSAssignOp;
class DivSOp;
class DivUAssignOp;
class DivUOp;
class EnumConstantOp;
class EnumDeclOp;
class EnumRefOp;
class ExprOp;
class ExtensionOp;
class FCmpOp;
class FieldDeclOp;
class FuncRefOp;
class GlobalRefOp;
class CaseOp;
class CondOp;
class CondYieldOp;
class DefaultOp;
class DoOp;
class ForOp;
class FuncOp;
class IfOp;
class LabelDeclOp;
class LabelStmtOp;
class SwitchOp;
class TypeYieldOp;
class ValueYieldOp;
class VarDeclOp;
class WhileOp;
class ImplicitCastOp;
class IndirectCallOp;
class InitListExprOp;
class LNotOp;
class MinusOp;
class MulFAssignOp;
class MulFOp;
class MulIAssignOp;
class MulIOp;
class NotOp;
class PlusOp;
class PostDecOp;
class PostIncOp;
class PreDecOp;
class PreIncOp;
class PredefinedExprOp;
class RecordMemberOp;
class RemFAssignOp;
class RemFOp;
class RemSAssignOp;
class RemSOp;
class RemUAssignOp;
class RemUOp;
class ReturnOp;
class SizeOfExprOp;
class SizeOfTypeOp;
class StmtExprOp;
class StructDeclOp;
class SubFAssignOp;
class SubFOp;
class SubIAssignOp;
class SubIOp;
class SubscriptOp;
class ThisOp;
class TranslationUnitOp;
class TypeDeclOp;
class TypeDefOp;
class TypeOfExprOp;
class UnionDeclOp;
}  // namespace ir::hl
namespace ir::core {
class BooleanAttr;
class StringLiteralAttr;
class FunctionType;
class BinLAndOp;
class BinLOrOp;
class ImplicitReturnOp;
class LazyOp;
class ScopeOp;
class SelectOp;
}  // namespace ir::core
namespace ir::unsup {
class UnsupportedType;
class UnsupportedDeclOp;
class UnsupportedStmtOp;
}  // namespace ir::unsup
}  // namespace mx
