vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO trail-of-forks/llvm-project
    REF ba5b66d60c3e1f1a138e753fcf2669fce0d89117
    SHA512 ad345fd870d01e78ac182613dc850d29dbd8c5b71bb5ba35cdb289b94cc315d434614f15dfa0ad09ff697f31c714bfa74a594e89ad1843e8be8ec8d4a23b22c5
    HEAD_REF pasta-llvmorg-17.0.4
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}/llvm"
    OPTIONS
        "-DLLVM_ENABLE_PROJECTS=clang;mlir"
        "-DLLVM_TARGETS_TO_BUILD=AArch64;X86;ARM"
        -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=ARM
        -DLLVM_APPEND_VC_REV=OFF
        -DLLVM_BUILD_DOCS=OFF
        -DLLVM_INCLUDE_DOCS=OFF
        -DLLVM_INCLUDE_EXAMPLES=OFF
        -DLLVM_BUILD_EXAMPLES=OFF
        -DLLVM_BUILD_LLVM_DYLIB=OFF
        -DLLVM_BUILD_TESTS=OFF
        -DLLVM_ENABLE_BINDINGS=OFF
        -DLLVM_ENABLE_OCAMLDOC=OFF
        -DLLVM_ENABLE_DIA_SDK=OFF
        -DLLVM_ENABLE_EH=ON
        -DLLVM_ENABLE_RTTI=ON
        -DLLVM_ENABLE_ASSERTIONS=ON
        -DLLVM_ENABLE_EXPENSIVE_CHECKS=OFF
        -DLLVM_ENABLE_FFI=OFF
        -DLLVM_ENABLE_WARNINGS=ON
        -DLLVM_INCLUDE_BENCHMARKS=OFF
        -DLLVM_INCLUDE_EXAMPLES=OFF
        -DLLVM_INCLUDE_TESTS=OFF
        -DLLVM_INCLUDE_TOOLS=ON
        -DLLVM_INSTALL_UTILS=ON
        -DLLVM_ENABLE_ZSTD=ON
)

vcpkg_cmake_install()