name: Build Docker

on:
  workflow_dispatch:
  schedule:
    # At 02:00 every day.
    - cron: "0 2 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-build

jobs:
  build-docker-ci:
    runs-on: multiplier
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and load Docker image
        uses: docker/build-push-action@v4
        with:
          context: .github/docker
          file: .github/docker/build.Dockerfile
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
