name: Build Docker

on:
  pull_request:
  schedule:
    # At 02:00 every day.
    - cron: "0 2 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-build

jobs:
  build-docker-ci:
    runs-on: multiplier
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and load Docker image
        run: |
          docker buildx build \
          --load \
          -f build.Dockerfile \
          -t ${REGISTRY}:{$IMAGE_NAME} \
          .
        working-directory: .github/docker
